### ISSUE TITLE
Little help with great thanks: I got many issues

### ISSUE THREAD

**Issue by dongdongqin** [Hironsan/BossSensor#12]
The first one is， it is probably version problem, I am newer and I will be very appreicated with your help;
When I run boss_train.py:

AttributeError: module 'tensorflow.python' has no attribute 'control_flow_ops

the second one is : when I run camera_reader.py:
I do not know what is the file of './store/model.h5', thank you!
 File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (D:\Build\h5py\h5py-2.6.0\h5py\_objects.c:2580)
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (D:\Build\h5py\h5py-2.6.0\h5py\_objects.c:2539)
  File "h5py\h5f.pyx", line 76, in h5py.h5f.open (D:\Build\h5py\h5py-2.6.0\h5py\h5f.c:1814)
OSError: Unable to open file (Unable to open file: name = './store/model.h5', errno = 2, error message = 'no such file or directory', flags = 0, o_flags = 0)

**Comment by dongdongqin** [comment]
I add the file : model.h5.
Another problem happened: I do not understand what the module should be in the config files. thank you! 
Using TensorFlow backend.
Model Loaded.
Traceback (most recent call last):
  File "F:/BossSensor/camera_reader.py", line 11, in <module>
    model.load()
  File "F:\BossSensor\boss_train.py", line 151, in load
    self.model = load_model(file_path)
  File "E:\Python 3.5\lib\site-packages\keras\models.py", line 126, in load_model
    raise ValueError('No model found in config file.')
ValueError: No model found in config file

**Comment by dongdongqin** [comment]
The first problem is:  the order I run the program is wrong. The file of boss_train.py should be executed firstly. And then camera_reader.py should be run secondly.

the second problem is solved by adding following content in the file of boss_train.py.
 import tensorflow as tf
tf.python.control_flow_ops = tf

thank you. Hope the problems can help more newers. thank you again!

**Comment by lionel126** [comment]
no ./store/ directory is the reason the first problem occurs
