### ISSUE TITLE
ZeroDivisionError: integer division or modulo by zero

### ISSUE THREAD

**Issue by julianL0veios** [Hironsan/BossSensor#16]
I'm a beginner,and i got those issues,what that means? 

gine/training.py", line 429, in data_generator_task
    generator_output = next(self._generator)
  File "/Users/zhangfei/anaconda3/envs/venv/lib/python3.5/site-packages/keras/preprocessing/image.py", line 662, in __next__
    return self.next(*args, **kwargs)
  File "/Users/zhangfei/anaconda3/envs/venv/lib/python3.5/site-packages/keras/preprocessing/image.py", line 708, in next
    index_array, current_index, current_batch_size = next(self.index_generator)
  File "/Users/zhangfei/anaconda3/envs/venv/lib/python3.5/site-packages/keras/preprocessing/image.py", line 645, in _flow_index
    current_index = (self.batch_index * batch_size) % n
ZeroDivisionError: integer division or modulo by zero

Traceback (most recent call last):
  File "boss_train.py", line 178, in <module>
    model.train(dataset, nb_epoch=10)
  File "boss_train.py", line 143, in train
    validation_data=(dataset.X_valid, dataset.Y_valid))
  File "/Users/zhangfei/anaconda3/envs/venv/lib/python3.5/site-packages/keras/models.py", line 935, in fit_generator
    initial_epoch=initial_epoch)
  File "/Users/zhangfei/anaconda3/envs/venv/lib/python3.5/site-packages/keras/engine/training.py", line 1600, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
UnboundLocalError: local variable 'epoch_logs' referenced before assignment

**Comment by julianL0veios** [comment]
its the image problem!
