### ISSUE TITLE
UnboundLocalError: local variable 'epoch_logs' referenced before assignment

### ISSUE THREAD

**Issue by jangdoohwan** [Hironsan/BossSensor#17]
/Users/icent/Documents/BossSensor/data/boss/dummy.jpg
X_train shape: (0, 64, 64, 3)
0 train samples
0 valid samples
1 test samples
____________________________________________________________________________________________________
Layer (type)                     Output Shape          Param #     Connected to                     
====================================================================================================
convolution2d_1 (Convolution2D)  (None, 64, 64, 32)    896         convolution2d_input_1[0][0]      
____________________________________________________________________________________________________
activation_1 (Activation)        (None, 64, 64, 32)    0           convolution2d_1[0][0]            
____________________________________________________________________________________________________
convolution2d_2 (Convolution2D)  (None, 62, 62, 32)    9248        activation_1[0][0]               
____________________________________________________________________________________________________
activation_2 (Activation)        (None, 62, 62, 32)    0           convolution2d_2[0][0]            
____________________________________________________________________________________________________
maxpooling2d_1 (MaxPooling2D)    (None, 31, 31, 32)    0           activation_2[0][0]               
____________________________________________________________________________________________________
dropout_1 (Dropout)              (None, 31, 31, 32)    0           maxpooling2d_1[0][0]             
____________________________________________________________________________________________________
convolution2d_3 (Convolution2D)  (None, 31, 31, 64)    18496       dropout_1[0][0]                  
____________________________________________________________________________________________________
activation_3 (Activation)        (None, 31, 31, 64)    0           convolution2d_3[0][0]            
____________________________________________________________________________________________________
convolution2d_4 (Convolution2D)  (None, 29, 29, 64)    36928       activation_3[0][0]               
____________________________________________________________________________________________________
activation_4 (Activation)        (None, 29, 29, 64)    0           convolution2d_4[0][0]            
____________________________________________________________________________________________________
maxpooling2d_2 (MaxPooling2D)    (None, 14, 14, 64)    0           activation_4[0][0]               
____________________________________________________________________________________________________
dropout_2 (Dropout)              (None, 14, 14, 64)    0           maxpooling2d_2[0][0]             
____________________________________________________________________________________________________
flatten_1 (Flatten)              (None, 12544)         0           dropout_2[0][0]                  
____________________________________________________________________________________________________
dense_1 (Dense)                  (None, 512)           6423040     flatten_1[0][0]                  
____________________________________________________________________________________________________
activation_5 (Activation)        (None, 512)           0           dense_1[0][0]                    
____________________________________________________________________________________________________
dropout_3 (Dropout)              (None, 512)           0           activation_5[0][0]               
____________________________________________________________________________________________________
dense_2 (Dense)                  (None, 2)             1026        dropout_3[0][0]                  
____________________________________________________________________________________________________
activation_6 (Activation)        (None, 2)             0           dense_2[0][0]                    
====================================================================================================
Total params: 6489634
____________________________________________________________________________________________________
Using real-time data augmentation.
Epoch 1/10
Traceback (most recent call last):
  File "/Users/icent/Documents/BossSensor/boss_train.py", line 181, in <module>
    model.train(dataset, nb_epoch=10)
  File "/Users/icent/Documents/BossSensor/boss_train.py", line 146, in train
    validation_data=(dataset.X_valid, dataset.Y_valid))
  File "/anaconda/envs/boss/lib/python3.5/site-packages/keras/models.py", line 874, in fit_generator
    pickle_safe=pickle_safe)
  File "/anaconda/envs/boss/lib/python3.5/site-packages/keras/engine/training.py", line 1485, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
UnboundLocalError: local variable 'epoch_logs' referenced before assignment

**Comment by OnlyBelter** [comment]
I have the same error:

`Total params: 6,489,634
Trainable params: 6,489,634
Non-trainable params: 0
____________________________________________________________________________________________________
Using real-time data augmentation.
Epoch 1/10
Exception in thread Thread-1:
Traceback (most recent call last):
  File "D:\tools\Anaconda3\envs\bossSensor\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "D:\tools\Anaconda3\envs\bossSensor\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "D:\tools\Anaconda3\envs\bossSensor\lib\site-packages\keras\engine\training.py", line 429, in data_generator_task
    generator_output = next(self._generator)
  File "D:\tools\Anaconda3\envs\bossSensor\lib\site-packages\keras\preprocessing\image.py", line 662, in __next__
    return self.next(*args, **kwargs)
  File "D:\tools\Anaconda3\envs\bossSensor\lib\site-packages\keras\preprocessing\image.py", line 708, in next
    index_array, current_index, current_batch_size = next(self.index_generator)
  File "D:\tools\Anaconda3\envs\bossSensor\lib\site-packages\keras\preprocessing\image.py", line 645, in _flow_index
    current_index = (self.batch_index * batch_size) % n
ZeroDivisionError: integer division or modulo by zero

Traceback (most recent call last):
  File "D:/tools/PyCharm-Project/BossSensor/boss_train.py", line 178, in <module>
    model.train(dataset, nb_epoch=10)
  File "D:/tools/PyCharm-Project/BossSensor/boss_train.py", line 143, in train
    validation_data=(dataset.X_valid, dataset.Y_valid))
  File "D:\tools\Anaconda3\envs\bossSensor\lib\site-packages\keras\models.py", line 935, in fit_generator
    initial_epoch=initial_epoch)
  File "D:\tools\Anaconda3\envs\bossSensor\lib\site-packages\keras\engine\training.py", line 1600, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
UnboundLocalError: local variable 'epoch_logs' referenced before assignment
`

How can I fix it??

**Comment by darrylsepeda** [comment]
Me too... get the same error:

```
Total params: 6,489,634
Trainable params: 6,489,634
Non-trainable params: 0
_________________________________________________________________
Using real-time data augmentation.
boss_train.py:143: UserWarning: Update your `fit_generator` call to the Keras 2 API: `fit_generator(<keras.pre..., epochs=10, steps_per_epoch=0, validation_data=(array([[[...)`
  validation_data=(dataset.X_valid, dataset.Y_valid))
Epoch 1/10
Traceback (most recent call last):
  File "boss_train.py", line 175, in <module>
    model.train(dataset, nb_epoch=10)
  File "boss_train.py", line 143, in train
    validation_data=(dataset.X_valid, dataset.Y_valid))
  File "/Users/darryl/Applications/miniconda2/envs/venv/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "/Users/darryl/Applications/miniconda2/envs/venv/lib/python3.5/site-packages/keras/models.py", line 1107, in fit_generator
    initial_epoch=initial_epoch)
  File "/Users/darryl/Applications/miniconda2/envs/venv/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "/Users/darryl/Applications/miniconda2/envs/venv/lib/python3.5/site-packages/keras/engine/training.py", line 1914, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
UnboundLocalError: local variable 'epoch_logs' referenced before assignment
```

eventhough already have the proper images as the resource

```
X_train shape: (4, 64, 64, 3)
4 train samples
3 valid samples
3 test samples
```

Can anyone explain what had happened?

**Comment by luis-i-reyes-castro** [comment]
Hello! I wanted to report that I got this error too, and I've found that in my case it was (at least partially) caused by having steps_per_epoch = 0. In this case line 1852 of "training.py" fails to enter the while loop which defines 'epochs_log'.
![epochs_log_error_cause](https://user-images.githubusercontent.com/28630745/27756455-2347ffa0-5dbd-11e7-96ca-7f4286a01055.jpg)

**Comment by hlnull** [comment]
check this issue: https://github.com/keras-team/keras/issues/450 for more details. Short answer is that `steps_per_epoch = 0`, as mentioned in https://github.com/Hironsan/BossSensor/issues/17#issuecomment-312389567.

**Comment by hlnull** [comment]
BTW, this issue has been fixed by https://github.com/keras-team/keras/pull/8854. Use the latest codes of keras shall fix this issue.
