### ISSUE TITLE
Error when checking : expected convolution2d_input_1

### ISSUE THREAD

**Issue by hmert** [Hironsan/BossSensor#4]
I have following error.

```
➜  BossSensor git:(master) ✗ python camera_reader.py
Using TensorFlow backend.
Model Loaded.
face detected
Traceback (most recent call last):
  File "camera_reader.py", line 36, in <module>
    result = model.predict(image)
  File "/Users/huseyinmert/Desktop/tmp_code/BossSensor/boss_train.py", line 159, in predict
    result = self.model.predict_proba(image)
  File "/usr/local/lib/python2.7/site-packages/keras/models.py", line 758, in predict_proba
    preds = self.predict(x, batch_size, verbose)
  File "/usr/local/lib/python2.7/site-packages/keras/models.py", line 671, in predict
    return self.model.predict(x, batch_size=batch_size, verbose=verbose)
  File "/usr/local/lib/python2.7/site-packages/keras/engine/training.py", line 1161, in predict
    check_batch_dim=False)
  File "/usr/local/lib/python2.7/site-packages/keras/engine/training.py", line 108, in standardize_input_data
    str(array.shape))
Exception: Error when checking : expected convolution2d_input_1 to have shape (None, 64, 64, 3) but got array with shape (1, 3, 64, 64)
```

**Comment by Hironsan** [comment]
what is your image_dim_ordering? th or tf?

> https://keras.io/backend/

**Comment by tornadoyi** [comment]
/Users/Jason/ML/BossSensor/camera_reader.py
Using TensorFlow backend.
Model Loaded.
Traceback (most recent call last):
face detected
  File "/Users/Jason/ML/BossSensor/camera_reader.py", line 36, in <module>
    result = model.predict(image)
  File "/Users/Jason/ML/BossSensor/boss_train.py", line 159, in predict
    result = self.model.predict_proba(image)
  File "/usr/local/lib/python2.7/site-packages/keras/models.py", line 758, in predict_proba
    preds = self.predict(x, batch_size, verbose)
  File "/usr/local/lib/python2.7/site-packages/keras/models.py", line 671, in predict
    return self.model.predict(x, batch_size=batch_size, verbose=verbose)
  File "/usr/local/lib/python2.7/site-packages/keras/engine/training.py", line 1161, in predict
    check_batch_dim=False)
  File "/usr/local/lib/python2.7/site-packages/keras/engine/training.py", line 108, in standardize_input_data
    str(array.shape))
Exception: Error when checking : expected convolution2d_input_1 to have shape (None, 64, 64, 3) but got array with shape (1, 3, 64, 64)
Cleaned up camera. 


I also have this error, how to resolve.

**Comment by bpgergo** [comment]
I also got this error. my image_dim_ordering is "tf". could it be the reason that I have different sized images in the training folders?

**Comment by lin65505578** [comment]
if use  tensorflow,change  model.predict to   "
    def predict(self, image):
        if image.shape != (1, 3, IMAGE_SIZE, IMAGE_SIZE):
            image = resize_with_pad(image)
            if K.image_dim_ordering() == 'th':
                image = image.reshape((1, 3, IMAGE_SIZE, IMAGE_SIZE))
            else:
                image = image.reshape((1, IMAGE_SIZE, IMAGE_SIZE ,3))
        image = image.astype('float32')
        image /= 255
        result = self.model.predict_proba(image)
        print(result)
        result = self.model.predict_classes(image)

        return result[0]
"

then the "Exception: Error when checking : expected convolution2d_input_1 to have shape (None, 64, 64, 3) but got array with shape (1, 3, 64, 64)"  disappear.
